1 - Importação das Bibliotecas que serão usadas

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score

2 - Carregamento dos dados

In [11]:
credito = pd.read_csv(r'F:\Estudando_Python\MachineLearn\Modelos_Preditivos\Credit.csv') # Carregando dados

3 - Visualizar

In [12]:
credito.shape   # Vizualisar quantidade de linhas e colunas

(1000, 21)

In [13]:
credito.head()  # Visualizar os primeiros 5 registros

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [14]:
credito.describe() # Vizualiar informaçaões sobre o dataset

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

Separando Previsores da Classe

In [15]:
previsores = credito.iloc[:,0:20] ## Captura a Coluna zero até a 19 (20-1) que são os atributos
classe = credito.iloc[:,20]       ## Captura a Coluna 20

classe.head()

0    good
1     bad
2    good
3    good
4     bad
Name: class, dtype: str

Transformando Atributos Categóricos em Numéricos

In [16]:
previsores = previsores.astype(object)
for col in [0, 2, 3, 5, 6, 8, 9, 11, 13, 14, 16, 18, 19]:
    previsores.iloc[:, col] = LabelEncoder().fit_transform(previsores.iloc[:, col])

Divindo dados entre Testes e Treinamentos

In [17]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split (
    previsores,
    classe,
    test_size = 0.3,
    random_state = 0
)

Criar e Treinar o Modelo

In [18]:
naive_bayes = GaussianNB() # Criar Modelo
naive_bayes.fit(x_treinamento, y_treinamento) # Treinar Modelo

GaussianNB()

Previsão

In [19]:
previsao = naive_bayes.predict(x_teste)
print(previsao)

['bad' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good' 'bad' 'bad'
 'bad' 'good' 'bad' 'good' 'good' 'good' 'good' 'bad' 'good' 'bad' 'good'
 'bad' 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'good' 'good' 'good'
 'good' 'good' 'bad' 'good' 'good' 'good' 'good' 'good' 'bad' 'good'
 'good' 'good' 'bad' 'bad' 'bad' 'bad' 'bad' 'good' 'bad' 'good' 'good'
 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good' 'good'
 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad'
 'good' 'good' 'bad' 'bad' 'good' 'bad' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'good'
 'good' 'bad' 'bad' 'good' 'good' 'good' 'bad' 'good' 'good' 'bad' 'good'
 'good' 'good' 'good' 'bad' 'bad' 'good' 'good' 'bad' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good'
 'good' 'good' 'bad' 'bad' 'bad' 'good' 'bad' 'good' 'good' 'good' 'bad'
 'bad' 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'bad' 'bad' 'bad' 'good' 'bad' 'bad' 'good' 'good' 'good'
 'good' 'bad' 'good' 'bad' 'bad' 'good' 'good' 'good' 'bad' 'good' 'good'
 'good' 'good' 'bad' 'bad' 'good' 'bad' 'good' 'good' 'good' 'good' 'good'
 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'bad' 'bad' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'bad'
 'bad' 'good' 'bad' 'good' 'good' 'bad' 'good' 'bad' 'bad' 'good' 'good'
 'good' 'good' 'bad' 'good' 'bad' 'bad' 'good' 'good' 'good' 'good' 'good'
 'bad' 'good' 'good' 'good' 'bad' 'bad' 'good' 'good' 'good' 'good' 'good'
 'bad' 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good'
 'good' 'good' 'bad' 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'bad'
 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'good'
 'good' 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'bad' 'good' 'bad' 'good']

Matrix de Confusão

In [20]:
confusao = confusion_matrix(y_teste, previsao)
print(confusao)

[[ 41  45]
 [ 42 172]]

Calcular Taxa de Acerto e Erro

In [21]:
taxa_de_acerto = accuracy_score(y_teste, previsao)
print("Acertos: ", taxa_de_acerto*100, "%" )
taxa_de_erro = 1 - taxa_de_acerto
print("Erros: ", taxa_de_erro*100, "%")

Acertos:  71.0 %
Erros:  29.000000000000004 %